# Prompt Options
PROMPT: 
  NUM_TOKENS: 5
  LOCATION: "prepend"
  INITIATION: "random"
  DEEP: False
  DROPOUT: 0.0

DATA_PATH: '/home/ste/Datasets/'
DEVICE: "cuda"

# Training/Inference parameters
BATCH_SIZE: 1
NUM_WORKERS: 4
LR: 5e-4
EVAL_EVERY: 1
EPOCHS: 10
WEIGHT_DECAY: 0.1 
LABEL_SMOOTHING: 0.
MAX_LENGTH: 1024
GRADIENT_ACC: False
# Wandb Config
USE_WANDB: True
PROJECT_NAME: "Standard Prompting on Audio Spectrogram Transformer"
EXP_NAME: "AST_STANDARD_PROMPT_01"